### ISSUE TITLE
There's no response after running the script

### ISSUE THREAD

**Issue by JulianGu001** [netinvent/usb_resetter#1]
Hi,

I tried you script to reset my USB dev,
but after run "usb_reset.py -l", 
Does it need some other precondition to use this script?

![usb_reset](https://user-images.githubusercontent.com/94002083/204097518-cbe413ad-44fa-4cdf-80d8-2ae736ccb956.png)

**Comment by deajan** [comment]
Well it seems that your system does not provide USB information through the path my script uses.
What's the output of `cat /sys/kernel/debug/usb/devices` ?

That path should exist on RHEL & Debian, more generally on any recent linux kernel.
I have no idea about RaspberryPI though.
What exact system do you have ?

**Comment by JulianGu001** [comment]
> 
Ok, thanks for your response.
The system info:
_pi@raspberrypi:~/Downloads $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs_




[usb.zip](https://github.com/netinvent/usb_resetter/files/10096594/usb.zip)

**Comment by deajan** [comment]
Thanks.
Did you by any chance not run the script as root ?
Just added [this commit](https://github.com/netinvent/usb_resetter/commit/c55e12271f4160a889e00af878938aa507adfc85) to add an error message when not run as root.

**Comment by deajan** [comment]
Closing since it seems that resolution was "run as root".
Feel free to open again if needed.
