### ISSUE TITLE
Same vendor id & product id

### ISSUE THREAD

**Issue by avilabss** [netinvent/usb_resetter#3]
I have a few usb dongles/modems, all identical, and they got same vendor id & product id. How can I reset a single device under this condition?

**Comment by deajan** [comment]
List devices attached to hubs, select the hub you want to reset, and go for it
```
usb_resetter -l
usb_resetter --reset-hub --hub /dev/bus/usb/001/002
```

Bear in mind that hubs might have multiple devices attached to it.

**Comment by avilabss** [comment]
I don't wanna reset the hub but instead I was wondering if we can make it work with usb port serial numbers?

**Comment by deajan** [comment]
My script parses output of /sys/kernel/debug/usb/devices
If you have your USB device serials in it, the script could be adapted.

**Comment by avilabss** [comment]
Hmm, I'll have to check. Also, Last time I accidentally used the vendor id and project id and all 5 modems got reset. But they weren't able to come back online until I powered the hub on and off. 

What could be the issue with this behaviour? I would expect all the modems to coming online.

**Comment by deajan** [comment]
Sorry... no context, no answer.
Diag logs would be required, but again, there are too many factors, hardware, modem type, usb version, kernel version....

I'm using this script myself to reset some Sierra MC7xxx modems, works for me at least.

**Comment by avilabss** [comment]
I'll be back with all the info soon, thanks for this amazing project and I hope this works out for my own applications, else I'll probably have to make a robo arm for myself 😂

**Comment by deajan** [comment]
Any news before I close this one ?

**Comment by avilabss** [comment]
Hi, feel free to close this one
